# Generated by Django 2.0.5 on 2018-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_bookrecommendpost_filmrecommendpost_gamerecommendpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surl', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('abstract', models.TextField()),
                ('subject', models.CharField(max_length=150)),
            ],
        ),
    ]
